### ISSUE TITLE
Input calculator does not clear when switched or reset

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#165] opened 2020-08-26 17:49 UTC
**Test device**
Dell and Lovelace
**Operating System**
Win 10 and ChromeOS
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/537
When you close the input calculator in one box when there is an input unentered (or entered but unusable) and open another box, that input still remains. It is also not cleared when you use the reset all button.
**Steps to reproduce**
1. Go to any screen and check the More Data box
2. Select a changeable option and enter some numbers. Don't press enter
3. Close the box and select another option, observe.
4. Close again without pressing enter
5. Press the orange reset all button
6. Select a changeable option and observe

**Visuals**
![doesnotresetinput](https://user-images.githubusercontent.com/41024075/91338374-10b8a800-e792-11ea-8eb3-fee556aed4a3.gif)
![savedinput](https://user-images.githubusercontent.com/41024075/91338380-12826b80-e792-11ea-8a43-8cb468b26ba8.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Collision Lab‬
URL: https://phet-dev.colorado.edu/html/collision-lab/1.1.0-dev.2/phet/collision-lab_en_phet.html
Version: 1.1.0-dev.2 2020-08-21 16:28:07 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jonathanolson** [comment] 2020-09-28 21:06
I believe this should be fixed by clearing the keypad when it's shown (done in the above commit).

@arouinfar is this acceptable, or do we need to check if the user selected a *different* box (i.e. keep the partial content if they open the same box)?

**Comment by arouinfar** [comment] 2020-09-29 03:22
@jonathanolson that sounds reasonable to me, and it's looking good in master. Since this was reported by QA, I'll tag for verification in the next test cycle.

**Comment by KatieWoe** [comment] 2020-10-20 22:21
Looks good in dev.10

**Comment by DevonQui** [comment] 2021-01-07 18:31
Just tested this issue and I was unable to reproduce it. Closing for now

**Closed by DevonQui** 2021-01-07 18:31 UTC
Labels: status:ready-for-qa, type:bug
