### ISSUE TITLE
Tunneling ball in 1D collisions

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#122] opened 2020-07-16 08:46 UTC
A user wrote into phethelp:
> I *think* there might be a bug in the Collisions simulation.
>
>Under the Advanved tab, if you choose one-dimension and have three balls
with different masses, say 0.1 kg, 1 kg, and 5 kg, you can see balls
"tunneling" through each other so that if they start out 1, 3, 2 you
might get 3, 1, 2 and then it will switch back to 1, 3, 2 or might
change to 3, 2, 1 (where the numbering is the ordering of the balls L-R
inside the rectangle). It happens mostly when the balls are moving fast,
although they never are traveling fast enough to approach speeds for QM
tunneling.
>
>I bring it up because it raises a question on whether or not this bug
might be affecting the simulation in other areas. If I assign it as an
online "lab" activity for a physics course, but the data is corrupt, it
makes it difficult for students to deal with the simulation data.

I was able to reproduce this bug in Flash if the initial velocities are high. It's also possible to do in the HTML5 version.

Initial state:
![image](https://user-images.githubusercontent.com/8419308/87649966-3459ee80-c70e-11ea-9333-ca7e924b7338.png)

At some point ball 1 tunnels through ball 2:
![image](https://user-images.githubusercontent.com/8419308/87649710-e349fa80-c70d-11ea-8afb-9636910b45f4.png)

**Comment by brandonLi8** [comment] 2020-07-27 16:15
This was addressed in #123, which has now been merged into master. Back to @arouinfar for review.

**Comment by arouinfar** [comment] 2020-07-30 16:18
Master is looking really good!! I haven't been able to reproduce the tunneling, but I think it would be good for QA to check on this too.

**Comment by KatieWoe** [comment] 2020-10-20 22:11
Haven't reproduced in dev.10

**Comment by brooklynlash** [comment] 2020-10-21 15:32
I noticed something similar on Windows 10 Chrome, but unsure if tunneling or just that the objects can overlap. Only works if you add balls in when the pink ball is at an area past where the new balls go in, and it looks like once they separate they don't go through each other again. 
![capacitortunnel2](https://user-images.githubusercontent.com/72031637/96742536-44721180-1380-11eb-88b4-878c05c67407.gif)

**Comment by KatieWoe** [comment] 2020-10-21 15:40
Great catch!. It might be a separate issue though. @arouinfar what is your verdict?

**Comment by arouinfar** [comment] 2020-10-22 02:20
Nice find @loganbraywork. I think @KatieWoe is correct, this looks like a slightly different issue, so I've opened #179.

**Comment by KatieWoe** [comment] 2021-01-07 17:48
Still seems fixed. Found something related to #179 but since it is a separate issue now, I think this can be closed. For 1.1.0 dev.13

**Closed by KatieWoe** 2021-01-07 17:48 UTC
Labels: status:ready-for-qa
