### ISSUE TITLE
On 1D, screen crashes if ball has nowhere to go

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/collision-lab#191] opened 2021-01-08 17:52 UTC
**Test device**
Lenovo ThinkPad

**Operating System**
Win10

**Browser**
Chrome

**Problem description**
Found when testing issues related to https://github.com/phetsims/collision-lab/issues/179, for https://github.com/phetsims/QA/issues/594. 
With 5 masses on the 1D collision screen, sometimes when the masses are increased they move around another mass instead of overlapping, but if there is not a space for one of the masses, the entire screen freezes. 
I don't get any warnings or errors on console besides the warning that the frame rate is slow.

**Visuals**
This is a long gif because it can take a long time to reproduce. 
https://drive.google.com/file/d/1iZMWeCl22P1EtiyEFjSXmM_AqV8I1wud/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Collision Lab‬
URL: https://phet-dev.colorado.edu/html/collision-lab/1.1.0-dev.13/phet/collision-lab_en_phet.html
Version: 1.1.0-dev.13 2021-01-06 18:20:45 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by jonathanolson** [comment] 2021-01-08 19:51
@brooklynlash any idea what I need to do to be able to view the above link? I haven't been able to watch the video reproduction yet.

**Comment by brooklynlash** [comment] 2021-01-08 20:35
@jonathanolson Oops, forgot to give access through the link. It should work now.

**Comment by jonathanolson** [comment] 2021-01-19 20:52
Ahh, I see that it can be set up where four balls can be positioned so that there is no valid position for the 5th ball if it has a mass increase:

![image](https://user-images.githubusercontent.com/480878/105091502-29856b00-5a5d-11eb-8298-c247f79a5407.png)

@arouinfar thoughts on how to tweak this?

In general, I've preferred methods of "handling overlap" where it iteratively bumps things apart (moving everything that overlaps), as this guarantees things will adjust to fit AND looks more natural instead of switching things to the "other" side. Do you think it's worth replacing the current "handle overlap" behavior fully? OR just detecting this case, and doing the more robust method there?

**Comment by arouinfar** [comment] 2021-01-19 21:28
> In general, I've preferred methods of "handling overlap" where it iteratively bumps things apart (moving everything that overlaps), as this guarantees things will adjust to fit AND looks more natural instead of switching things to the "other" side. Do you think it's worth replacing the current "handle overlap" behavior fully? OR just detecting this case, and doing the more robust method there?

I think the current method of "handling overlap" is working nicely, so I wouldn't want to fully change the behavior. Let's try detecting this specific case and employing a more robust method only as necessary.

**Comment by jonathanolson** [comment] 2021-01-19 23:20
Added the robust handling after (it shouldn't usually need to kick in). @KatieWoe can you confirm?

**Comment by KatieWoe** [comment] 2021-01-19 23:39
This fix looks good on master

**Comment by arouinfar** [comment] 2021-01-20 00:06
Looks good @jonathanolson

**Comment by loganbraywork** [comment] 2021-01-21 02:37
Seems to be fixed as of https://github.com/phetsims/QA/issues/599

**Closed by loganbraywork** 2021-01-21 02:37 UTC
Labels: status:ready-for-qa, type:bug
