### ISSUE TITLE
Freezing behavior when stepping back with inelastic behavior.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#203] opened 2021-01-26 19:25 UTC
For https://github.com/phetsims/QA/issues/599. Seen while looking at https://github.com/phetsims/collision-lab/issues/183, and it seems to be related.
While on the 2D screen, I had an inelastic collision, and was stepping it back to see if behavior differed between that and moving forward. While stepping back, the screen froze and the console gave a large number of errors that seemed to keep climbing as the sim was frozen. I have been trying to reproduce, and have not had luck so far, but I will continue to try.
<img width="833" alt="frozenscreen" src="https://user-images.githubusercontent.com/41024075/105894397-78894e00-5fd1-11eb-81f3-4684f3a4d19f.png">

**Comment by KatieWoe** [comment] 2021-01-26 22:50
Managed to reproduce a few times on Mac 10.13 Chrome. Still not exactly sure what causes it, and recreating the starting conditions doesn't seem to work.
![Screen Shot 2021-01-26 at 3 37 50 PM](https://user-images.githubusercontent.com/41024075/105916501-3b7f8480-5fee-11eb-9556-7f066fb4fdb7.png)
![Screen Shot 2021-01-26 at 3 35 46 PM](https://user-images.githubusercontent.com/41024075/105916504-3c181b00-5fee-11eb-9157-769814dc126c.png)

**Comment by arouinfar** [comment] 2021-01-28 18:25
@jonathanolson at some point we disabled the step back button for elasticity =/= 0. I'd be fine with going back to that if it would resolve this issue.

**Comment by jonathanolson** [comment] 2021-02-02 01:03
>  recreating the starting conditions doesn't seem to work.

That's probably rounding errors at work, since we're only getting the rounded values displayed visually.

**Comment by jonathanolson** [comment] 2021-02-02 01:26
For debugging this, I'd probably need someone to reproduce while devtools were open (to catch it and debug).

However I'm also running into cases where it seems the numerical imprecision (https://github.com/phetsims/collision-lab/issues/183#issuecomment-771279058), so I think removing step-back for inelastic collisions here is the correct decision.

**Comment by arouinfar** [comment] 2021-02-03 16:07
> However I'm also running into cases where it seems the numerical imprecision (#183 (comment)), so I think removing step-back for inelastic collisions here is the correct decision.

Sounds good @jonathanolson. Let's proceed.

**Comment by jonathanolson** [comment] 2021-02-04 16:05
Implemented the removal of inelastic step-back, can you verify?

**Comment by arouinfar** [comment] 2021-02-04 17:24
Looks good @jonathanolson!

**Comment by DevonQui** [comment] 2021-02-09 19:32
This has been fixed. In Explore 2D, if elasticity isn't 100%, the step-back button is disabled as expected. Closing

**Closed by DevonQui** 2021-02-09 19:32 UTC
Labels: status:ready-for-qa, type:bug
