### ISSUE TITLE
CT ensure color components are finite and not NaN

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#80] opened 2020-05-28 21:37 UTC
```
collision-lab : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590679192703/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1590679192703%22%2C%22timestamp%22%3A1590682246082%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Ensure color components are finite and not NaN
Error: Assertion failed: Ensure color components are finite and not NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590679192703/assert/js/assert.js:22:13)
at Color.updateColor (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590679192703/scenery/js/util/Color.js:371:15)
at Color.setRGBA (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590679192703/scenery/js/util/Color.js:268:10)
at Color.setAlpha (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590679192703/scenery/js/util/Color.js:257:45)
at PathCanvasNode.paintCanvas (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590679192703/collision-lab/js/common/view/PathCanvasNode.js:135:44)
at CanvasNodeDrawable.paintCanvas (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590679192703/scenery/js/display/drawables/CanvasNodeDrawable.js:66:12)
at CanvasBlock.renderDrawable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590679192703/scenery/js/display/CanvasBlock.js:369:14)
at CanvasBlock.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590679192703/scenery/js/display/CanvasBlock.js:169:12)
at BackboneDrawable.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590679192703/scenery/js/display/BackboneDrawable.js:254:33)
at DOMBlock.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590679192703/scenery/js/display/DOMBlock.js:54:22)
id: Bayes Chrome
Snapshot from 5/28/2020, 9:19:52 AM
```

**Comment by brandonLi8** [comment] 2020-05-28 21:48
Thanks @KatieWoe.

**Comment by brandonLi8** [comment] 2020-05-28 23:43
Able to reproduce by:

- path on, inelastic
- start sim, wait till ball hits border,
- leaving sim on, move ball to next to another wall

This is definitely due to the Collision Detector

**Comment by brandonLi8** [comment] 2020-05-28 23:50
Fix committed above, closing.

**Closed** 2020-05-28 23:50 UTC
Labels: type:automated-testing
