### ISSUE TITLE
Rewinding doesn't handle initial collision for touching balls

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/collision-lab#205] opened 2021-02-02 01:10 UTC
Just noticed this, and it's slightly bugging me. Not sure how to handle:

1. Explore 2d.
2. Move a ball to touch another so they will immediately collide e.g. 
![image](https://user-images.githubusercontent.com/480878/106537874-7551fe80-64b8-11eb-80fc-04ac85215694.png)
3. Play for a short time then pause: 
![image](https://user-images.githubusercontent.com/480878/106537905-81d65700-64b8-11eb-9310-76d666c3cb32.png)
4. Rewind fully : 
![image](https://user-images.githubusercontent.com/480878/106537931-8d298280-64b8-11eb-8088-75caae6c9e1a.png)

It shows the velocities before the collision (like they just happened).

This could technically be solved by rewinding an insignificant amount of extra time, potentially? Thoughts?

**Comment by arouinfar** [comment] 2021-02-03 16:05
> This could technically be solved by rewinding an insignificant amount of extra time, potentially? Thoughts?

Let's try this out @jonathanolson.

**Comment by jonathanolson** [comment] 2021-02-04 16:48
Looks like it's working nicely, can you try in master after the above commit?

**Comment by arouinfar** [comment] 2021-02-04 17:23
Looks good in master @jonathanolson

**Comment by DevonQui** [comment] 2021-02-09 19:35
This has been fixed in rc.2. Closing

**Comment by KatieWoe** [comment] 2021-02-12 19:43
It looks like this can happen sometimes, and it seems easier to see if some of the balls have 0 velocity. I reproduced with a set up in Explore 2D, but this is easier to replicate. May be seeing diminishing returns at this point, so I'm assigning @arouinfar to see if it is worth addressing.

https://user-images.githubusercontent.com/41024075/107814628-75ab8e80-6d2f-11eb-9df0-a82f358b8396.MOV

**Comment by jonathanolson** [comment] 2021-02-15 02:14
That seems tricky to handle at this stage, I'm likely to break other things (since this definitely wasn't included in the design or original implementation).

**Comment by arouinfar** [comment] 2021-02-15 03:24
Thanks @KatieWoe, but given @jonathanolson's assessment, I'm going to close.

**Closed by arouinfar** 2021-02-15 03:24 UTC
Labels: type:bug

**Comment by KatieWoe** [comment] 2021-03-11 17:02
This has been closed, but I wanted to document what this looks like in 2D.

https://user-images.githubusercontent.com/41024075/110824908-b7592780-8250-11eb-801e-d7d62ff49e16.MP4
