### ISSUE TITLE
User reported issue: physics bug in Collision Lab

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#4] opened 2019-09-19 19:50 UTC
Momentum is not conserved in the Collisions lab and the mass moves the wrong way in a very extreme situation that came up in class....

For 1D case...

1) Make one mass very small but very fast. 2) Make other mass very big but very slow.

If small mass has slightly more momentum you'd think the big mass would move backwards......

And, it does unless you increase the speed of the simulation.... in that special case the error due to the big time steps is enough to make the big mass actually move in the WRONG direction!!!.

**Comment by veillette** [comment] 2019-09-19 19:50
from https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3515

**Comment by veillette** [comment] 2019-12-14 20:14
I look into this issue and I have a good idea of what is going on.
In essence, the time-discretization approach breaks down when the speed of a particle is very fast. and the timestep ( The user refer to it as  the speed of the simulation) is large.
Under these conditions, the two particles in a head on collision can pass through each other since the displacement $\DeltaT \velocity$ becomes so large that it exceeds the radius of the large particle.
The small particle goes from the left of the large particle to the right without going through the collision algorithm (since the two particles don't overlap).

Part of the problem arises from the unlimited values for the velocity. User can entered values (from the keyboard) for velocity that exceeds the speed of light. A solution to this problem is to validate the  values entered by the user to some appropriate values (say 10 m/s) Since the smallest radius of a ball is approximately 0.25 m , then in 1/60 of a second, it can only move 0.16 m , which is less that the diameter of the ball.

**Comment by brandonLi8** [comment] 2020-07-27 16:14
>  A solution to this problem is to validate the values entered by the user to some appropriate values (say 10 m/s) Since the smallest radius of a ball is approximately 0.25 m , then in 1/60 of a second, it can only move 0.16 m , which is less that the diameter of the ball.

We tried limiting the velocity to 3 m/s. However, we still saw balls going through each other, because the user can infinitely increase the kinetic energy by increasing mass. We also reliable reproduced tunneling particularly when high velocity balls were stacked on top of each other and bounced off a wall (which now makes sense because our collision engine only handled one collision at a time).

In #123, I addressed all of these problems by converting the collision detection to a priori (where collisions are detected beforehand) and added the ability to handle multiple collisions within a large time step. Closing.

**Closed by brandonLi8** 2020-07-27 16:14 UTC
Labels: type:legacy-bug
